apiVersion: v1
kind: Service
metadata:
  name: pdf-generator
  labels:
    app.kubernetes.io/name: pdf-generator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pdf-generator
  ports:
    - port: 80
      targetPort: http
      name: http
